[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = []

[project.optional-dependencies]
dev = ["ruff"]
