name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ci-secret
      ENABLE_FAKE_MODELS: "true"
      DEBUG: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort ruff pytest pytest-django pillow
      - name: Black
        run: |
          black --check .
      - name: Ruff
        run: |
          python -m pip install ruff
          python -m ruff check .
          python -m ruff format --check .
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          DJANGO_SETTINGS_MODULE: breast_risk_site.settings
          DJANGO_SECRET_KEY: ci-secret
          ENABLE_FAKE_MODELS: true
          DEBUG: false
        run: pytest -q --tb=short

