name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ci-secret
      ENABLE_FAKE_MODELS: "true"
      DEBUG: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort ruff pytest pytest-django pillow
      - name: Lint
        run: |
          ruff check .
          black --check .
          isort --check-only .
      - name: Tests
        run: |
          pytest -q
